apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  type: ClusterIP
  clusterIP: "172.16.2.2"
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    name: postgresql
