apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
spec:
  type: ClusterIP
  clusterIP: "172.16.2.3"
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    name: redis
